# Generated by Django 5.1.2 on 2024-10-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0003_alter_church_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchrecord',
            name='service_name',
        ),
        migrations.AlterField(
            model_name='churchrecord',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_record', to='industry.church'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='industry.church')),
            ],
        ),
    ]
