# Generated by Django 5.1.2 on 2024-10-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0004_remove_churchrecord_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchrecord',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_record', to='industry.service'),
        ),
    ]
