# Generated by Django 5.1.2 on 2024-10-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0006_remove_churchrecord_id_remove_offering_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='record',
        ),
        migrations.DeleteModel(
            name='ChurchRecord',
        ),
    ]
