# Generated by Django 5.1.2 on 2024-10-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0008_churchrecord_offering_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchrecord',
            name='children',
            field=models.PositiveIntegerField(default=0, verbose_name='number of children'),
        ),
        migrations.AddField(
            model_name='churchrecord',
            name='female',
            field=models.PositiveIntegerField(default=0, verbose_name='number of females'),
        ),
        migrations.AddField(
            model_name='churchrecord',
            name='male',
            field=models.PositiveIntegerField(default=0, verbose_name='number of males'),
        ),
    ]
