# Generated by Django 5.1.2 on 2024-10-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0009_churchrecord_children_churchrecord_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
