# Generated by Django 5.1.2 on 2024-10-30 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0010_church_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='date_established',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
