# Generated by Django 5.1.2 on 2024-10-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0011_church_date_established'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='end_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='church',
            name='owner',
            field=models.CharField(max_length=200, verbose_name='Founder'),
        ),
    ]
