# Generated by Django 5.1.2 on 2024-10-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0012_service_end_time_service_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='currency',
            field=models.CharField(choices=[('USD', 'Us Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNH', 'Chinese Renminbi'), ('HKD', 'Hong Kong Dollar'), ('NZD', 'New Zealand Dollar'), ('NGN', 'Nigerian Naira')], default='USD'),
        ),
    ]
