# Generated by Django 5.1.2 on 2024-10-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0013_alter_offering_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offering',
            options={'ordering': ['denomination']},
        ),
        migrations.AlterField(
            model_name='offering',
            name='currency',
            field=models.CharField(choices=[('USD', 'Us Dollar'), ('NGN', 'Nigerian Naira'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNH', 'Chinese Renminbi'), ('HKD', 'Hong Kong Dollar'), ('NZD', 'New Zealand Dollar')], default='USD'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='denomination',
            field=models.DecimalField(decimal_places=2, max_digits=6, unique=True),
        ),
    ]
