# Generated by Django 5.1.2 on 2024-11-01 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0014_alter_offering_options_alter_offering_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='date_established',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
