# Generated by Django 5.1.2 on 2024-11-05 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0015_alter_church_date_established_alter_church_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='about',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='church',
            name='managers',
            field=models.ManyToManyField(null=True, related_name='%(class)s_industry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='church',
            name='website',
            field=models.URLField(blank=True, help_text='Prefix url scheme to website e.g https://www.example.com'),
        ),
    ]
