# Generated by Django 5.1.2 on 2024-11-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0016_church_about_alter_church_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='day',
            field=models.CharField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thu'), ('Friday', 'Fri')], default='Monday'),
        ),
    ]
