# Generated by Django 5.1.2 on 2025-03-25 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0017_service_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='managers',
            field=models.ManyToManyField(related_name='%(class)s_industry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, default='Member'),
        ),
        migrations.AlterField(
            model_name='service',
            name='day',
            field=models.CharField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thu'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], default='Monday'),
        ),
    ]
