# Generated by Django 5.1.2 on 2025-03-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0018_alter_church_managers_alter_member_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
    ]
