# Generated by Django 5.1.2 on 2025-03-31 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0019_alter_church_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='date_established',
            field=models.DateField(default=django.utils.timezone.now, help_text='Format: yyyy-mm-dd', verbose_name='Established'),
        ),
        migrations.AlterField(
            model_name='church',
            name='head_pastor',
            field=models.CharField(max_length=300, verbose_name='pastor'),
        ),
        migrations.AlterField(
            model_name='churchrecord',
            name='sermon_title',
            field=models.CharField(max_length=200),
        ),
    ]
