# Generated by Django 5.1.2 on 2025-04-05 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0020_alter_church_date_established_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchrecord',
            name='service_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Format: yyyy-mm-dd', verbose_name='service date'),
        ),
    ]
