# Generated by Django 5.1.2 on 2025-04-05 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0022_remove_churchrecord_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchrecord',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Format: yyyy-mm-dd', verbose_name='service date'),
        ),
    ]
