# Generated by Django 5.1.2 on 2025-05-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0023_churchrecord_service_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='churchrecord',
            options={'ordering': ['-service_date', '-edit_date']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
    ]
