# Generated by Django 5.1.2 on 2025-05-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0024_alter_church_options_alter_churchrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
