# Generated by Django 5.1.2 on 2025-05-19 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0025_service_special_service_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Format: yyyy-mm-dd'),
        ),
    ]
